slam_toolbox:
  ros__parameters:
    use_sim_time: false

    # Frames
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan

    mode: mapping

    # If your LD19 is noisy, these help:
    minimum_time_interval: 0.2
    transform_timeout: 0.2

    # Keep it lightweight on the Pi
    resolution: 0.05
    max_laser_range: 12.0

    # Conservative settings to start
    do_loop_closing: true
    loop_search_maximum_distance: 3.0
