teleop_twist_joy_node:
  ros__parameters:
    requre_enable_button: true
    enable_button: 4 #LB
    enable_turbo_button: 5 #RB

    axis_linear:
      x: 1 # left stick vertical
    scale_linear:
      x: 0.6
    scale_linear_turbo:
      x: 1.0

    axis_angular:
      yaw: 3 # right stick horizontal
    scale_angular:
      yaw: 1.8
    scale_angular_turbo:
      yaw: 2.5